### PR TITLE
suggested_solution

### PR DESCRIPTION
**Pull request by omermassa**
@moshe-h-m

### CODE REVIEW

**Comment by moshe-h-m** [comment]
good job ommer!!
but you need to add the fither that will be limitition in the number of the suggestion
solve it

**Comment by moshe-h-m** [comment]
> good job @omermassa !! but you need to add the fither that will be limitition in the number of the suggestion solve it

**Comment by omermassa** [comment]
@moshe-h-m bug fixed in the solution

**Comment by moshe-h-m** [comment]
good jub @omermassa 
חיילך לאורייתא
והעיקר אור בהירות הדרך

**Pull request closed without merging**
